### ISSUE TITLE
Game Crash by Start

### ISSUE THREAD

**Issue by Titoo8899** [Nomi-CEu/RealBench-Nomi-CEu#1]
Hi, I have a Problem with your Mod. Then I start in Minecraft Forge the Client Crash and give me this out.
I hope it help you to fix the Problem.

Crash Report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Fluidlogged API Plugin (Fluidlogged-API-v1.9.0.3-mc1.12.2.jar)
  Immersive Vehicles (Immersive+Vehicles-1.12.2-22.3.0.jar)
  SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.4.jar)
  Disable Elyctra Degradation (Infinilytra-1.12.2-1.0.0.jar)
  MixinLoader (Locks-1.12.2-3.0.0.jar)
  MixinBooter (!mixinbooter-7.0.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 12/3/22 10:26 AM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraft.client.gui.GuiMainMenu.handler$zbi000$addCustomSpMpButtons(GuiMainMenu.java:727)
	at net.minecraft.client.gui.GuiMainMenu.func_73969_a(GuiMainMenu.java)
	at net.minecraft.client.gui.GuiMainMenu.func_73866_w_(GuiMainMenu.java:185)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1018)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:545)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

(MixinBooter) Mixins in Stacktrace:
	net.minecraft.client.Minecraft:
		net.geforcemods.securitycraft.mixin.camera.MixinMinecraft (securitycraft.mixins.json)
	net.minecraft.client.gui.GuiMainMenu:
		mcinterface1122.mixin.client.MixinMainMenu (mts.mixins.json)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.gui.GuiMainMenu.handler$zbi000$addCustomSpMpButtons(GuiMainMenu.java:727)
	at net.minecraft.client.gui.GuiMainMenu.func_73969_a(GuiMainMenu.java)
	at net.minecraft.client.gui.GuiMainMenu.func_73866_w_(GuiMainMenu.java:185)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1018)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:545)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1824203024 bytes (1739 MB) / 2147483648 bytes (2048 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 23 mods loaded, 0 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID              | Version      | Source                                | Signature                                |
	|:----- |:--------------- |:------------ |:------------------------------------- |:---------------------------------------- |
	|       | minecraft       | 1.12.2       | minecraft.jar                         | None                                     |
	|       | mcp             | 9.42         | minecraft.jar                         | None                                     |
	|       | FML             | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	|       | forge           | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	|       | mixinbooter     | 7.0          | minecraft.jar                         | None                                     |
	|       | boatoverhaul    | 1.0          | BoatOverhaul-Forge-1.12.2-1.1.0.jar   | None                                     |
	|       | securitycraft   | v1.9.4       | [1.12.2]+SecurityCraft+v1.9.4.jar     | None                                     |
	|       | timelesspower   | 1.2          | [1.12.2]TimelessPower-1.2.jar         | None                                     |
	|       | configuration   | 1.0.3.1      | configuration-1.12.2-1.0.3.1.jar      | None                                     |
	|       | darkstone       | 1.12.2-1.0   | darkstone-1.12.2-1.0.jar              | None                                     |
	|       | fbp             | 0.7          | fbp-0.7.jar                           | None                                     |
	|       | firstaid        | 1.6.21       | firstaid-1.6.21.jar                   | None                                     |
	|       | fluidlogged_api | 1.9.0.3      | Fluidlogged-API-v1.9.0.3-mc1.12.2.jar | None                                     |
	|       | mts             | 22.3.0       | Immersive+Vehicles-1.12.2-22.3.0.jar  | None                                     |
	|       | mts             | 22.4.0-BETA1 | Immersive+Vehicles-1.12.2-22.4.0.jar  | None                                     |
	|       | keywizard       | 1.12.2-1.7.3 | keywizard-1.12.2-1.7.3.jar            | None                                     |
	|       | laa_tailoring   | 1.0.0        | laa-tailoring.jar                     | None                                     |
	|       | locks           | 3.0.0        | Locks-1.12.2-3.0.0.jar                | None                                     |
	|       | payday          | 3.0          | payday-3.2-1.12.2.jar                 | None                                     |
	|       | quickstore      | 1.4          | quickstore-1.5.jar                    | None                                     |
	|       | jianghun        | 1.0          | RGB+Chat+0.5.jar                      | None                                     |
	|       | snowtime        | 1.0-SNAPSHOT | snowtime-1.0-SNAPSHOT.jar             | None                                     |
	|       | ignitingarrows  | 1.12.2-INDEV | IgnitingArrows-1.12.2-1.0.0.jar       | None                                     |

	Loaded coremods (and transformers): 
Fluidlogged API Plugin (Fluidlogged-API-v1.9.0.3-mc1.12.2.jar)
  git.jbredwards.fluidlogged_api.mod.asm.ASMHandler$Transformer
Immersive Vehicles (Immersive+Vehicles-1.12.2-22.3.0.jar)
  mcinterface1122.patches.PhosphorSlicePatch
SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.4.jar)
  
Disable Elyctra Degradation (Infinilytra-1.12.2-1.0.0.jar)
  staples.infinilytra.asm.transformer.EntityLivingBaseTransformer
MixinLoader (Locks-1.12.2-3.0.0.jar)
  
MixinBooter (!mixinbooter-7.0.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 526.98' Renderer: 'NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 526.98, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz

**Comment by IntegerLimit** [comment]
Try updating mixinbooter to 8.9.

**Comment by IntegerLimit** [comment]
Also, this issue is not related to our mod, we do nothing on the main menu.

**Comment by IntegerLimit** [comment]
Closing. RealBench is not even loaded in the log.
